---
- hosts: db
  vars:
    db_password: password
  tasks:
    - name: copy the db
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name:update MariaDB to present version
      become: yes
      apt: name=MariaDB-server,MariaDB-client update_cache=yes state=present

    - name: manage service 
      become: yes
      systemd: name=mariadb state=started enabled=yes

    - name: sends file to remote location
      #the file will be sent to "/tmp/mariadb_answers.txt"
      #permissions for the file are -rw-r--r--  
      template: src=db/mariadb_answers.txt dest=/tmp/mariadb_answers.txt mode=0644

    - name:
      become: yes
      shell: /usr/bin/mysql_secure_installation </tmp/mariadb_answers.txt

    - name:unpacking an archive
      #unpacking an archive from "db/db.tgz" to "~/"
      unarchive: src=db/db.tgz dest=~/ mode=0644

    - name: 
      command: ./make_databases.sh {{ db_password }} localhost chdir=~/db
      ignore_errors: True
