---
- hosts: db

  vars_files:
   - secret.yml
  tasks:
    - name: inlclude secret.yml
      include_vars: secret.yml

    - name: Copying MariaDB repos
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name:  Installing//Updateing MariaDB/ CLient
      become: yes
      yum: name=MariaDB-client update_cache=yes state=present

    - name: Extracting db.tgz to ~/
      become: yes
      unarchive: src=db/db.tgz dest=~/ mode=0777


    - name: run script
      become: yes
      command: ./make_databases.sh {{ db_password }} rds.cpeg32lappd9.us-west-2.rds.amazonaws.com chdir=~/db
      ignore_errors: True
